name: Create markdown indexes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          # Avoid this error - This repository exceeded its LFS budget. The account responsible for the budget should increase it to restore access.

#      - name: Pull Git LFS files
#        run: git lfs pull
      - name: Disable Git LFS
        run: rm .gitattributes

      - uses: gacts/directory-listing@v1
        with:
          target: ./
          # target: .
          # ignore: |
          #   build/**
          #   **/index.html
          #   node_modules/**,**/*.log
          # show-hidden: true
          # overwrite: true

      - name: Rewrite Links to Viewer
        run: |
          # The base URL for your LFS files on GitHub's media server
          MEDIA_BASE="https://media.githubusercontent.com/media/vishvasa/book-pub/master"
          
          # The Google Viewer prefix to force the PDF to display inline
          VIEWER_PREFIX="https://docs.google.com/viewer?url="

          # This SED command:
          # 1. Finds href="./something.pdf"
          # 2. Captures 'something.pdf'
          # 3. Replaces it with the Viewer + Media URL
          sed -i "s|href=\"\./\([^\" ]*\.pdf\)\"|href=\"$VIEWER_PREFIX$MEDIA_BASE/\1\"|g" index.html

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true # git history growth - even on non-src branches - makes cloning slow.