name: Create markdown indexes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          # Avoid this error - This repository exceeded its LFS budget. The account responsible for the budget should increase it to restore access.

#      - name: Pull Git LFS files
#        run: git lfs pull
      - name: Disable Git LFS
        run: rm .gitattributes

      - uses: gacts/directory-listing@v1
        with:
          target: ./
          # target: .
          # ignore: |
          #   build/**
          #   **/index.html
          #   node_modules/**,**/*.log
          # show-hidden: true
          # overwrite: true
      - name: Run Python Link Rewriter
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python rewrite_lfs_links.py

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true # git history growth - even on non-src branches - makes cloning slow.